evaluation_cfg:
  metrics:
    - CollisionMetric
    - NavigabilityMetric
    - OutOfBoundMetric
    - OpeningClearanceMetric
  output_dir: ./output_eval
  save_blend_file: True
  vlm: GPT
  use_existing_matching: True
  use_empty_matching_result: True
  support_metric_use_existing_support_type_assessment: False
  no_eval: False
  verbose: False

input_cfg:
  root_dir: ./input
  scene_methods:
    - SceneWeaver
  method_use_simple_architecture: []
  scene_mode: range
  scene_range: [0, 5]
  scene_list: []
  annotation_file: ./input/annotations.csv

render_cfg:
  normal_render_tasks:
    - scene_top
    - obj_solo
  semantic_render_tasks: []
  semantic_color_reference: null
